### ISSUE TITLE
filename

### ISSUE THREAD

**Issue by koteitan** [rpakr-googology/Googology#1]
You might want to rename the yabasic codes into the name without space charactors (for example 'LPpSExpansion.yab'). When I try to execute them, they couldn't be executed with space charactor as it is.

```
koteitan@bach:~/rpakr/github$ yabasic 'LPpS Expansion'
---Error: could not open 'LPpS': No such file or directory
koteitan@bach:~/rpakr/github$ mv 'LPpS Expansion' LPpSExpansion.yab
koteitan@bach:~/rpakr/github$ yabasic LPpSExpansion.yab
0,1,2
Sequence: 0,1,2
Limit Case
BR=1
Delta=1
Expansion:
0,1
0,1,1,2
0,1,1,2,2,3
0,1,1,2,2,3,3,4
0,1,1,2,2,3,3,4,4,5
```

**Comment by rpakr-googology** [comment]
Is 'LPpS_Expansion.yab' or 'LPpS-Expansion.yab' fine?

**Comment by koteitan** [comment]
I tried and both are ok.

**Comment by rpakr-googology** [comment]
I will rename 'LPpS Expansion' to 'LPpS_Expansion' and 'TONPrSS to TON' to 'TONPrSS_to_TON'.

**Comment by rpakr-googology** [comment]
Done.
